// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using VozdelEste.Models.Monedas;
//
//    var monedas = Monedas.FromJson(jsonString);

namespace VozdelEste.Models.Monedas
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Monedas
    {
        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("terms")]
        public Uri Terms { get; set; }

        [JsonProperty("privacy")]
        public Uri Privacy { get; set; }

        [JsonProperty("timestamp")]
        public long Timestamp { get; set; }

        [JsonProperty("source")]
        public string Source { get; set; }

        [JsonProperty("quotes")]
        public Quotes Quotes { get; set; }
    }

    public partial class Quotes
    {
        [JsonProperty("UYUUSD")]
        public double Uyuusd { get; set; }

        [JsonProperty("UYUEUR")]
        public double Uyueur { get; set; }

        [JsonProperty("UYUBRL")]
        public double Uyubrl { get; set; }
    }

    public partial class Monedas
    {
        public static Monedas FromJson(string json) => JsonConvert.DeserializeObject<Monedas>(json, VozdelEste.Models.Monedas.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Monedas self) => JsonConvert.SerializeObject(self, VozdelEste.Models.Monedas.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
